### ISSUE TITLE
Make install does not create the dfm folder in /etc/xdg/

### ISSUE THREAD

**Issue by i28v** [cglindkamp/dfm#2]
When I run `sudo make install` I get this error:
`install: cannot create regular file '/etc/xdg/dfm/rc': No such file or directory`
This can be fixed by creating the folder manually, but it was kind of annoying.
Could you please add something to the makefile to create the folder automatically?
Thanks.

**Comment by cglindkamp** [comment]
Thanks for the report, this should be fixed now.
